# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef35e908cf22afd5b4ccf485020039c9d41817c66c093cab1575058634efde10e039f449f801ceb53eeffb422a34b8371cb9ca49f3b497fe1d779d82deb51075

test:
  secret_key_base: 22e25612d2e4147a5c9f721840561c736ff44dc564aa4292a930f9e9c933809e3d00768512310d867e62699a2f97532a897d684229df7eab3a9990bb7652331d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
